---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Print variable anisble Facts
      debug:
        msg: >
          The Default Address of {{ ansible_fqdn }} is {{ ansible_default_ipv4.address }}

